# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: 
- name: SpacyNLP
# - name: SpacyTokenizer
- name: WhitespaceTokenizer
  case_sensitive: false
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
  features: [["low", "upper"],["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "upper", "digit", "pattern"],["low", "upper"]]
- name: DucklingHTTPExtractor
  url: http://35.199.26.99:8000
  dimensions:
  - time
  # - email
  # - number
  # - amount-of-money
  # - distance
  locale: en-GB
  # timezone: Europe/Berlin
  # timezone: Asia/Calcutta
- name: EntitySynonymMapper
# - name: SklearnIntentClassifier
- name: CountVectorsFeaturizer
  oov_token: oov
- name: EmbeddingIntentClassifier
  epochs: 50
  intent_tokenization_flag: true
  intent_split_symbol: "+"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.15
    core_threshold: 0.15
    fallback_action_name: fallback_action
    # fallback_core_action_name: fallback_action
    # fallback_nlu_action_name: fallback_action
    # deny_suggestion_intent_name: out_of_scope
  - name: FormPolicy