# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: 
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: DucklingHTTPExtractor
  url: http://35.245.19.88:8000
  dimensions:
  - time
  - email
  - number
  - amount-of-money
  - distance
  locale: "en-IN"
  timezone: "Asia/Kolkata"
- name: SklearnIntentClassifier

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.15
    core_threshold: 0.15
    fallback_action_name: fallback_action
    # fallback_core_action_name: fallback_action
    # fallback_nlu_action_name: fallback_action
    # deny_suggestion_intent_name: out_of_scope